### ISSUE TITLE
latest pull not working 

### ISSUE THREAD

**Issue by kingwill101** [papyros/papyros-shell#90]
ive freshly cloned all the necessary repos but i keep getting alot of errors, plus i wasnt able to build our greenisland branch because cmake keeps complaining that it cant find qtwaylandscanner

```
[kingwill@kingtech build]$ greenisland --shell io.papyros.shell
QML debugging is enabled. Only use this in a safe environment.
greenisland.protocols.wlshell.trace: GreenIsland::WlShellGlobal::WlShellGlobal(QObject*)
greenisland.protocols.wlshell.trace: virtual const wl_interface* GreenIsland::WlShellGlobal::interface() const
greenisland.protocols.wlshell.trace: virtual const wl_interface* GreenIsland::WlShellGlobal::interface() const
greenisland.protocols.xdgshell.trace: GreenIsland::XdgShellGlobal::XdgShellGlobal(GreenIsland::Compositor*)
greenisland.protocols.xdgshell.trace: virtual const wl_interface* GreenIsland::XdgShellGlobal::interface() const
greenisland.protocols.xdgshell.trace: virtual const wl_interface* GreenIsland::XdgShellGlobal::interface() const
greenisland.protocols.gtkshell.trace: GreenIsland::GtkShellGlobal::GtkShellGlobal(QObject*)
greenisland.protocols.gtkshell.trace: virtual const wl_interface* GreenIsland::GtkShellGlobal::interface() const
greenisland.protocols.gtkshell.trace: virtual const wl_interface* GreenIsland::GtkShellGlobal::interface() const
greenisland.screenbackend.native: Screen added "DVI-I-1" QRect(0,32 1440x868)
greenisland.compositor: Added primary output "DVI-I-1" with geometry QRect(0,0 1440x868)
greenisland.compositor: Compositor ready, notify systemd on ""
greenisland.compositor: Showing window for output "DVI-I-1" QRect(0,0 1440x868)
greenisland.compositor: Loading scene on output "DVI-I-1" QRect(0,0 1440x868)
greenisland.compositor: Loading "io.papyros.shell" shell for output "DVI-I-1" QRect(0,0 1440x868)
file:///usr/share/greenisland/io.papyros.shell/Compositor.qml:110: ReferenceError: Units is not defined
file:///usr/share/greenisland/io.papyros.shell/Compositor.qml:140: ReferenceError: Units is not defined
file:///usr/share/greenisland/io.papyros.shell/Compositor.qml:149: ReferenceError: Units is not defined
file:///usr/share/greenisland/io.papyros.shell/Compositor.qml:161: ReferenceError: Units is not defined
file:///usr/share/greenisland/io.papyros.shell/Compositor.qml:179: ReferenceError: Units is not defined
greenisland.compositor: QML scene loaded successfully
greenisland.compositor: Scene load time: 215 ms
greenisland.compositor: EGL version: 1.4 (DRI2)
greenisland.compositor: EGL vendor: Mesa Project
greenisland.compositor: EGL client APIs: OpenGL OpenGL_ES OpenGL_ES2 OpenGL_ES3 
greenisland.compositor: EGL extensions: EGL_MESA_drm_image EGL_MESA_configless_context EGL_WL_bind_wayland_display
    EGL_KHR_image_base EGL_KHR_image_pixmap EGL_KHR_image EGL_KHR_get_all_proc_addresses
    EGL_KHR_gl_texture_2D_image EGL_KHR_gl_texture_cubemap_image
    EGL_KHR_gl_renderbuffer_image EGL_KHR_surfaceless_context
    EGL_KHR_create_context EGL_NOK_swap_region EGL_NOK_texture_from_pixmap
    EGL_CHROMIUM_sync_control EGL_EXT_image_dma_buf_import
    EGL_NV_post_sub_buffer 
greenisland.compositor: Surface created QWaylandQuickSurface(0x183d300)
file:///usr/share/greenisland/io.papyros.shell/Shell.qml:25:1: module "org.kde.kcoreaddons" is not installed
```

**Comment by iBelieve** [comment]
I don't know what Linux distro you're on, but to build Green Island on Arch, I use the `cmake` line taken from [this AUR package](https://aur.archlinux.org/packages/gr/greenisland-git/PKGBUILD):

```
cmake ../${_gitname} \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DLIB_INSTALL_DIR=lib \
    -DLIBEXEC_INSTALL_DIR=lib \
    -DQML_INSTALL_DIR=lib/qt/qml \
    -DKDE_INSTALL_USE_QT_SYS_PATHS=ON \
    -DQtWaylandScanner_EXECUTABLE=/usr/lib/qt/bin/qtwaylandscanner \
    -DCMAKE_BUILD_TYPE=RelWithDebInfo
```

As for the import error, you need [KDeclarative](http://api.kde.org/frameworks-api/frameworks5-apidocs/kdeclarative/html/) installed. Again, if you're on Arch, the package is `kdeclarative`. I've updated the README to list the additional dependencies.

Hope this helps!

**Comment by kingwill101** [comment]
That fixes most of my issues but I'm still having several reference errors

**Comment by kingwill101** [comment]
@iBeliever  still not much luck on my side. Below here is the output of my build
im on arch

```
/home/kingwill/papyros-repos/greenisland/src/libgreenisland/screen/fakescreenbackend.cpp: In member function 'void GreenIsland::FakeScreenBackend::screenAdded(GreenIsland::ScreenOutput*)':
/home/kingwill/papyros-repos/greenisland/src/libgreenisland/screen/fakescreenbackend.cpp:89:5: error: 'QWaylandOutputMode' was not declared in this scope
     QWaylandOutputMode *mode =
     ^
/home/kingwill/papyros-repos/greenisland/src/libgreenisland/screen/fakescreenbackend.cpp:89:25: error: 'mode' was not declared in this scope
     QWaylandOutputMode *mode =
                         ^
/home/kingwill/papyros-repos/greenisland/src/libgreenisland/screen/fakescreenbackend.cpp:90:17: error: expected type-specifier before 'QWaylandOutputMode'
             new QWaylandOutputMode(QStringLiteral("defaultMode"),
                 ^
In file included from /usr/include/qt/QtCore/qregexp.h:41:0,
                 from /usr/include/qt/QtCore/qstringlist.h:40,
                 from /usr/include/qt/QtCore/qlist.h:1026,
                 from /usr/include/qt/QtCore/qhash.h:40,
                 from /usr/include/qt/QtCore/qdebug.h:38,
                 from /usr/include/qt/QtCore/qloggingcategory.h:38,
                 from /usr/include/qt/QtCore/QLoggingCategory:1,
                 from /home/kingwill/papyros-repos/greenisland/src/libgreenisland/screen/screenbackend.h:30,
                 from /home/kingwill/papyros-repos/greenisland/src/libgreenisland/screen/fakescreenbackend.h:30,
                 from /home/kingwill/papyros-repos/greenisland/src/libgreenisland/screen/fakescreenbackend.cpp:27:
/home/kingwill/papyros-repos/greenisland/src/libgreenisland/screen/fakescreenbackend.cpp:90:36: error: expected primary-expression before ')' token
             new QWaylandOutputMode(QStringLiteral("defaultMode"),
                                    ^
/home/kingwill/papyros-repos/greenisland/src/libgreenisland/screen/fakescreenbackend.cpp:93:13: error: 'class GreenIsland::Output' has no member named 'setModes'
     output->setModes(QWaylandOutputModeList() << mode);
             ^
/home/kingwill/papyros-repos/greenisland/src/libgreenisland/screen/fakescreenbackend.cpp:93:45: error: 'QWaylandOutputModeList' was not declared in this scope
     output->setModes(QWaylandOutputModeList() << mode);
                                             ^
/home/kingwill/papyros-repos/greenisland/src/libgreenisland/screen/nativescreenbackend.cpp: In member function 'void GreenIsland::NativeScreenBackend::changeMode(QScreen*)':
/home/kingwill/papyros-repos/greenisland/src/libgreenisland/screen/nativescreenbackend.cpp:153:5: error: 'QWaylandOutputMode' was not declared in this scope
     QWaylandOutputMode *mode =
     ^
/home/kingwill/papyros-repos/greenisland/src/libgreenisland/screen/nativescreenbackend.cpp:153:25: error: 'mode' was not declared in this scope
     QWaylandOutputMode *mode =
                         ^
/home/kingwill/papyros-repos/greenisland/src/libgreenisland/screen/nativescreenbackend.cpp:154:17: error: expected type-specifier before 'QWaylandOutputMode'
             new QWaylandOutputMode(QStringLiteral("defaultMode"),
                 ^
In file included from /usr/include/qt/QtCore/qcoreapplication.h:38:0,
                 from /usr/include/qt/QtGui/qguiapplication.h:37,
                 from /usr/include/qt/QtGui/QGuiApplication:1,
                 from /home/kingwill/papyros-repos/greenisland/src/libgreenisland/screen/nativescreenbackend.cpp:28:
/home/kingwill/papyros-repos/greenisland/src/libgreenisland/screen/nativescreenbackend.cpp:154:36: error: expected primary-expression before ')' token
             new QWaylandOutputMode(QStringLiteral("defaultMode"),
                                    ^
/home/kingwill/papyros-repos/greenisland/src/libgreenisland/screen/nativescreenbackend.cpp:159:13: error: 'class GreenIsland::Output' has no member named 'setModes'
     output->setModes(QWaylandOutputModeList() << mode);
             ^
/home/kingwill/papyros-repos/greenisland/src/libgreenisland/screen/nativescreenbackend.cpp:159:45: error: 'QWaylandOutputModeList' was not declared in this scope
     output->setModes(QWaylandOutputModeList() << mode);
                                             ^
src/libgreenisland/CMakeFiles/GreenIsland.dir/build.make:737: recipe for target 'src/libgreenisland/CMakeFiles/GreenIsland.dir/screen/fakescreenbackend.cpp.o' failed
make[2]: *** [src/libgreenisland/CMakeFiles/GreenIsland.dir/screen/fakescreenbackend.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
src/libgreenisland/CMakeFiles/GreenIsland.dir/build.make:760: recipe for target 'src/libgreenisland/CMakeFiles/GreenIsland.dir/screen/nativescreenbackend.cpp.o' failed
make[2]: *** [src/libgreenisland/CMakeFiles/GreenIsland.dir/screen/nativescreenbackend.cpp.o] Error 1
CMakeFiles/Makefile2:464: recipe for target 'src/libgreenisland/CMakeFiles/GreenIsland.dir/all' failed
make[1]: *** [src/libgreenisland/CMakeFiles/GreenIsland.dir/all] Error 2
Makefile:146: recipe for target 'all' failed
make: *** [all] Error 2
[  1%] [  2%] [  2%] [  3%] Automatic moc for target greenislandplugin
Automatic moc for target GreenIsland
Automatic moc for target greenisland-launcher
Automatic moc for target greenisland
[  3%] [  3%] Built target greenislandplugin_automoc
[  3%] Built target greenisland-launcher_automoc
Built target greenisland_automoc
[  3%] Built target GreenIsland_automoc
[  4%] [  5%] Automatic moc for target plasma
Automatic moc for target greenisland-screencaster
[  8%] Built target greenisland-launcher
[  8%] [  8%] Built target plasma_automoc
Built target greenisland-screencaster_automoc
[ 15%] Built target greenisland-screencaster
[ 16%] [ 17%] [ 18%] [ 19%] Building CXX object src/libgreenisland/CMakeFiles/GreenIsland.dir/screen/fakescreenbackend.cpp.o
Building CXX object src/libgreenisland/CMakeFiles/GreenIsland.dir/screen/nativescreenbackend.cpp.o
Building CXX object src/libgreenisland/CMakeFiles/GreenIsland.dir/protocols/wl-shell/wlshell.cpp.o
Building CXX object src/libgreenisland/CMakeFiles/GreenIsland.dir/protocols/wl-shell/wlshellsurface.cpp.o
/home/kingwill/papyros-repos/greenisland/src/libgreenisland/screen/nativescreenbackend.cpp: In member function 'void GreenIsland::NativeScreenBackend::changeMode(QScreen*)':
/home/kingwill/papyros-repos/greenisland/src/libgreenisland/screen/nativescreenbackend.cpp:153:5: error: 'QWaylandOutputMode' was not declared in this scope
     QWaylandOutputMode *mode =
     ^
/home/kingwill/papyros-repos/greenisland/src/libgreenisland/screen/nativescreenbackend.cpp:153:25: error: 'mode' was not declared in this scope
     QWaylandOutputMode *mode =
                         ^
/home/kingwill/papyros-repos/greenisland/src/libgreenisland/screen/nativescreenbackend.cpp:154:17: error: expected type-specifier before 'QWaylandOutputMode'
             new QWaylandOutputMode(QStringLiteral("defaultMode"),
                 ^
In file included from /usr/include/qt/QtCore/qcoreapplication.h:38:0,
                 from /usr/include/qt/QtGui/qguiapplication.h:37,
                 from /usr/include/qt/QtGui/QGuiApplication:1,
                 from /home/kingwill/papyros-repos/greenisland/src/libgreenisland/screen/nativescreenbackend.cpp:28:
/home/kingwill/papyros-repos/greenisland/src/libgreenisland/screen/nativescreenbackend.cpp:154:36: error: expected primary-expression before ')' token
             new QWaylandOutputMode(QStringLiteral("defaultMode"),
                                    ^
/home/kingwill/papyros-repos/greenisland/src/libgreenisland/screen/nativescreenbackend.cpp:159:13: error: 'class GreenIsland::Output' has no member named 'setModes'
     output->setModes(QWaylandOutputModeList() << mode);
             ^
/home/kingwill/papyros-repos/greenisland/src/libgreenisland/screen/nativescreenbackend.cpp:159:45: error: 'QWaylandOutputModeList' was not declared in this scope
     output->setModes(QWaylandOutputModeList() << mode);
                                             ^
/home/kingwill/papyros-repos/greenisland/src/libgreenisland/screen/fakescreenbackend.cpp: In member function 'void GreenIsland::FakeScreenBackend::screenAdded(GreenIsland::ScreenOutput*)':
/home/kingwill/papyros-repos/greenisland/src/libgreenisland/screen/fakescreenbackend.cpp:89:5: error: 'QWaylandOutputMode' was not declared in this scope
     QWaylandOutputMode *mode =
     ^
/home/kingwill/papyros-repos/greenisland/src/libgreenisland/screen/fakescreenbackend.cpp:89:25: error: 'mode' was not declared in this scope
     QWaylandOutputMode *mode =
                         ^
/home/kingwill/papyros-repos/greenisland/src/libgreenisland/screen/fakescreenbackend.cpp:90:17: error: expected type-specifier before 'QWaylandOutputMode'
             new QWaylandOutputMode(QStringLiteral("defaultMode"),
                 ^
In file included from /usr/include/qt/QtCore/qregexp.h:41:0,
                 from /usr/include/qt/QtCore/qstringlist.h:40,
                 from /usr/include/qt/QtCore/qlist.h:1026,
                 from /usr/include/qt/QtCore/qhash.h:40,
                 from /usr/include/qt/QtCore/qdebug.h:38,
                 from /usr/include/qt/QtCore/qloggingcategory.h:38,
                 from /usr/include/qt/QtCore/QLoggingCategory:1,
                 from /home/kingwill/papyros-repos/greenisland/src/libgreenisland/screen/screenbackend.h:30,
                 from /home/kingwill/papyros-repos/greenisland/src/libgreenisland/screen/fakescreenbackend.h:30,
                 from /home/kingwill/papyros-repos/greenisland/src/libgreenisland/screen/fakescreenbackend.cpp:27:
/home/kingwill/papyros-repos/greenisland/src/libgreenisland/screen/fakescreenbackend.cpp:90:36: error: expected primary-expression before ')' token
             new QWaylandOutputMode(QStringLiteral("defaultMode"),
                                    ^
/home/kingwill/papyros-repos/greenisland/src/libgreenisland/screen/fakescreenbackend.cpp:93:13: error: 'class GreenIsland::Output' has no member named 'setModes'
     output->setModes(QWaylandOutputModeList() << mode);
             ^
/home/kingwill/papyros-repos/greenisland/src/libgreenisland/screen/fakescreenbackend.cpp:93:45: error: 'QWaylandOutputModeList' was not declared in this scope
     output->setModes(QWaylandOutputModeList() << mode);
                                             ^
src/libgreenisland/CMakeFiles/GreenIsland.dir/build.make:760: recipe for target 'src/libgreenisland/CMakeFiles/GreenIsland.dir/screen/nativescreenbackend.cpp.o' failed
make[2]: *** [src/libgreenisland/CMakeFiles/GreenIsland.dir/screen/nativescreenbackend.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
src/libgreenisland/CMakeFiles/GreenIsland.dir/build.make:737: recipe for target 'src/libgreenisland/CMakeFiles/GreenIsland.dir/screen/fakescreenbackend.cpp.o' failed
make[2]: *** [src/libgreenisland/CMakeFiles/GreenIsland.dir/screen/fakescreenbackend.cpp.o] Error 1
CMakeFiles/Makefile2:464: recipe for target 'src/libgreenisland/CMakeFiles/GreenIsland.dir/all' failed
make[1]: *** [src/libgreenisland/CMakeFiles/GreenIsland.dir/all] Error 2
Makefile:146: recipe for target 'all' failed
make: *** [all] Error 2
```

```
my workflow

rm -r qml*
rm -r papyros*
rm -r green*
rm -r qtwayland
git clone -b output55 https://github.com/maui-packages/qtwayland
git clone https://github.com/glenfordwilliams/qml-extras
git clone https://github.com/glenfordwilliams/qml-material
git clone https://github.com/papyros/greenisland.git
git clone https://github.com/papyros/papyros-shell.git

cd qtwayland 
qmake
make -j4 
make -j4 install
cd ..

cd qml-material
#git remote add upstream https://github.com/papyros/qml-material
#git fetch upstream
qmake
make -j4
make -j4 install

cd ..

cd qml-extras
#git remote add upstream https://github.com/papyros/qml-material
#git fetch upstream
qmake
make -j4
make -j4 install

cd ..


cd greenisland 
#git remote add upstream https://github.com/papyros/greenisland
git fetch
git checkout feature/window_manager
git pull
mkdir build; cd build

cmake ../${_gitname} \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DLIB_INSTALL_DIR=lib \
    -DLIBEXEC_INSTALL_DIR=lib \
    -DQML_INSTALL_DIR=lib/qt/qml \
    -DKDE_INSTALL_USE_QT_SYS_PATHS=ON \
    -DQtWaylandScanner_EXECUTABLE=/usr/lib/qt/bin/qtwaylandscanner \
    -DCMAKE_BUILD_TYPE=RelWithDebInfo
make -j4 
make -j4 install

cd ..
cd papyros-shell
mkdir build; cd build
cmake .. -DCMAKE_INSTALL_PREFIX=/usr -DQML_INSTALL_DIR=lib/qt/qml
make -j4 
make -j4 install

cd ..
```
